### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by takealook00** [zju3dv/animatable_nerf#34]
Hello, Sida. I have encountered the problem of EOFError.
Since I am using Windows, I assumed that it caused problem.
Is there anything that you can give me help?
Thanks

![image](https://user-images.githubusercontent.com/40441643/182062202-10a6a482-34f5-41bb-9853-62dcc698755b.png)

**Comment by pengsida** [comment]
I am not familiar with the Windows environment.

**Comment by dendenxu** [comment]
Hi, we did not test the code on Windows. I would recommend you to run it on a Linux environment because lots of features of some deep learning frameworks like PyTorch is not fully supported on Windows.
If you don't have access to a Linux machine, you can try out [WSL2](https://docs.microsoft.com/en-us/windows/wsl/about)!
