### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by bhargavbompalli** [zju3dv/animatable_nerf#35]
Thanks for sharing the code, just wondering if this is possible to run on a custom dataset?

**Comment by dendenxu** [comment]
Yes! Of course it's possible to run our method on a custom dataset, but note that there might be some data processing to be done to match the expected directory structure for animatable_nerf.

We'll release a guide on how to prepare your custom dataset soon. In the meantime, you can reference [this guide](https://github.com/zju3dv/neuralbody/tree/master/tools/custom) on [neuralbody](https://github.com/zju3dv/neuralbody) since the expected directory structure of [animatable_nerf](https://github.com/zju3dv/animatable_nerf) and [neuralbody](https://github.com/zju3dv/neuralbody) are similar.

**Comment by ivanvoid** [comment]
> We'll release a guide on how to prepare your custom dataset soon

It's been a around a year, I assume you already published this guide, can you link it here? 
thank you
