### ISSUE TITLE
Why need to retrain the blend weight fields of unseen human poses?

### ISSUE THREAD

**Issue by tpzou** [zju3dv/animatable_nerf#46]
Congrats on this great work, and thanks a lot for open-sourcing this project!

1. I wonder why we need to retrain the blend weight fields of unseen human poses? It seems can directly use the Nerf and neural blend weight field for 3D animation.

2. And what‘s the 'Rh" mean? Is it the same of `global_orient` in `SMPL`?

       # transform smpl from the world coordinate to the smpl coordinate 
        params_path = os.path.join(self.data_root, cfg.params,
                                   '{}.npy'.format(i))
        params = np.load(params_path, allow_pickle=True).item()
        Rh = params['Rh'].astype(np.float32)
        Th = params['Th'].astype(np.float32)

**Comment by dendenxu** [comment]
Hi, zou! Thanks for the feedback.
1. As stated in Section 3.2.1 of the [paper](https://arxiv.org/abs/2203.08133), by default, we're unable to directly use the latent code for training poses to generate blend weight fields for novel poses. And conditioning the neural blend weight fields on poses proves to be problematic to generalize to unseen poses. This also shows that retrieving the latent code for the closest training pose (as we did for the color latent code) will not produce satisfactory results (due to the inability of neural blend weight fields to generalize to novel poses).
2. Yes, `Rh` indeed represents the global orientation of the human. Specifically `Rh` is the angle-axis format rotation to transform a canonically oriented model (refer to the tpose of the `SMPL` model) to its world orientation. If you're interested, you can check out the code related to transforming from and to world coordinate space (which takes `Rh` as one of its inputs) to grasp a better understanding of this process: https://github.com/zju3dv/animatable_nerf/blob/c8b9a140d032a70a6e0e428c1e03aa39e9c95980/lib/utils/blend_utils.py#L25

**Comment by dendenxu** [comment]
Oh, Now I understand your question.
1. Of course, one can use the Marching Cubes results on the canonical NeRF model and extract a set of blend weights for the vertices to animate the mesh (you can even try to extract a texture or vertex colors for the mesh). This would result in an animation pipeline similar to that of the Computer Graphics industry.
    What we described in the paper and in the comment I wrote above is about **animating the whole implicit representation** (which requires backward skinning since the canonical NeRF model lives in canonical space).
    Generally speaking, animating the extracted mesh would lead to much lower resolution and blocky results (animating the mesh for `SDF-PDF` might result in smoother surface). And the appearance would just not be on par with animating the implicit representation since extracting the mesh using Marching Cubes or extract vertex colors is an extremely lossy process.
    It might be a quite interesting research topic if one wants to deploy an Animatable NeRF model.
2. Please refer to my comment in https://github.com/zju3dv/animatable_nerf/issues/45 .

**Comment by tpzou** [comment]
Thanks, I got it
