### ISSUE TITLE
Question of custom data

### ISSUE THREAD

**Issue by tpzou** [zju3dv/animatable_nerf#47]
Hi, I'm having some problems implementing my own data with `prepare_lbs_meta.py`. I try to test the cope with [CAPE](https://cape.is.tue.mpg.de/) dataset.  The param of CAPE is 
```
for k, v in cape_param.items():
    print(k)
    print(v.shape)

print: transl
        (3,)
        v_cano
        (6890, 3)
        pose
        (72,)
        v_posed
        (6890, 3)
```
I performed the following processing to fite  `prepare_lbs_meta.py.` 

```
vertices = cape_param["v_posed"].reshape(6890, 3)

shapes = betas.reshape(1, 10)
Th = cape_param["transl"].reshape(1, 3)
Rh = cape_param["pose"][:, :3].reshape(1, 3)
poses = cape_param["pose"].reshape(1, 72)
poses[:, :3] = 0
save_dict = {"shapes":shapes, "poses":poses, "Rh":Rh, "Th":Th, }

out_param = os.path.join(param_dir, f'{i:04d}')
out_verti = os.path.join(vertices_dir, f'{i:04d}')
np.save(out_param, save_dict)
np.save(out_verti, vertices)
```
But I find the result of `get_tpose_blend_weights()` seems not right

![5d35b75caee6d8921d6936d6e949e2d](https://user-images.githubusercontent.com/54886980/192782717-60c54b4c-1d94-4ede-aef5-27c7ce7a05b3.jpg)

from left to right are the posed vertices,  GT T-pose vertices, and process T-pose vertices. I simply checked the code against `SMPL`， there didn't seem to be any problems. 

Am I doing it the right way? Can you give me some advice? Thanks

**Comment by dendenxu** [comment]
Hi! Thank you for your feedback!

Actually, we've only implemented code to run Animatable NeRF on fitted SMPL and rendered images. I haven't tested whether using other model works under current pipeline. Although at first glance CAPE and SMPL have similar topology, thus it would probably work without too much pain (and probably improve the reconstruction since CAPE fits clothed human better).

`prepare_lbs_meta.py` will prepare input files under the `lbs` folder of the corresponding dataset. And as the script's name suggests, it will prepare metadata to perform LBS on the fitted SMPL of the dataset in question. The outputs `weights.npy`, `joints.npy`, `tvertices.npy` and `bigpose_vertices.npy` correspond to the SMPL model fitted to the data instead of the dataset itself.

I'm not sure I fully understand what your problem is so it would be great if you elaborate on what do you mean by: 
> But I find the result of get_tpose_blend_weights() seems not right

From the image you posted I can see that the posed vertices **actually contains pose-dependent deformation** (**Notice the bulging on the elbows**). Thus when you unpose the posed mesh, you should also remove the pose-dependent deformation of CAPE to get the original canonical mesh. In Animtable NeRF we simply ignore the pose-dependent effect of SMPL (When converting SMPL from canonical to world space, we only apply LBS without pose-dependent deformation), so this phenomenon of bulging elbow is kind of expected. I would advise using the provided GT canonical mesh and pose it to world space without pose-denpendent effect (you'll notice some bulging or contraction on the posed mesh). 

We're planning on improving documentation about preparing your custom dataset but I haven't been able to find time for that.

**Comment by tpzou** [comment]
I see... So the data processing is correct, right?

**Comment by dendenxu** [comment]
Looks good enought to me. But you should be aware of the caveats mentioned in my previous comment https://github.com/zju3dv/animatable_nerf/issues/47#issuecomment-1261173614 when proceeding.

**Comment by tpzou** [comment]
Hi, @dendenxu ， sorry to bother you again. I'm confused about the `z_vals` in the code. Whether it refers to the distance along the ray or the distance on the z-coordinate axis？Its performance in `depth_map` and  [tpose_nerf_network.py ](https://github.com/zju3dv/animatable_nerf/blob/master/lib/networks/bw_deform/tpose_nerf_network.py#:~:text=raw2alpha%20%3D%20lambda,*%20dists) looks contradictory.

**Comment by dendenxu** [comment]
@tpzou No big deal. `z_vals` means distance along the ray (consider world coordinates). We called it `z_vals` (and use it to compute the depth map) because we consider depth as originating from the camera center, instead of the camera plane (perspective v.s. orthogonal projection).
